language: cpp

sudo: false

matrix:
  include:
    - env: CMAKE_CXX="g++" BUILD_TYPE="Debug"
      os: linux

before_script:
  # print out some version numbers
  - pip install carbin
  - $CMAKE_CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
script:
  - make -j2
  - make test