language: cpp

sudo: false

matrix:
  include:
    - env: CMAKE_CXX="g++" BUILD_TYPE="Debug"
      os: linux

before_script:
  # print out some version numbers
  - pip install carbin --user
  - $CMAKE_CXX --version
  - cmake --version
script:
  - make build
  - make test